# Generated by Django 4.2.7 on 2026-09-18 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_trip_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0008_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('qr', 'QR'), ('pin', 'PIN')], max_length=3)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_event', to='bookings.booking')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_events', to='companies.trip')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_boardings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
