# Generated by Django 4.2.7 on 2026-09-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_boardingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='verification_pin',
            field=models.CharField(default='1234', max_length=10),
        ),
    ]
