# Generated by Django 4.2.7 on 2026-09-18 20:09

import bookings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_latitude_and_more'),
        ('bookings', '0010_booking_verification_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='boardingevent',
            name='method',
            field=models.CharField(choices=[('qr', 'QR Scan'), ('pin', 'PIN Entry')], max_length=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default=bookings.models.generate_booking_number, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='verification_pin',
            field=models.CharField(default=bookings.models.generate_verification_pin, max_length=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('digital', 'Digital (M-Pesa/Card)'), ('cash', 'Cash')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_number'], name='bookings_bo_booking_03d631_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
    ]
