# Generated by Django 6.1.1 on 2026-09-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement_status',
            field=models.CharField(choices=[('not_ready', 'Not Ready'), ('eligible', 'Eligible'), ('settled', 'Settled'), ('refunded', 'Refunded')], default='not_ready', max_length=20),
        ),
    ]
