# Generated by Django 4.2.7 on 2026-09-24 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0014_payment_refund_amount_payment_refund_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('breakdown', 'Breakdown'), ('accident', 'Accident'), ('road_blocked', 'Road Blocked'), ('stage_issue', 'Stage Issue'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='reported', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='companies.trip')),
            ],
            options={
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['trip', 'status'], name='bookings_in_trip_id_f5856e_idx'), models.Index(fields=['reported_at'], name='bookings_in_reporte_e8f166_idx')],
            },
        ),
    ]
