# Generated by Django 4.2.7 on 2026-09-24 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled')], default='held', max_length=20)),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_hold', to='bookings.booking')),
            ],
        ),
    ]
