# Generated by Django 4.2.7 on 2026-09-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_bookinghold'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghold',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
