# Generated by Django 4.2.7 on 2026-09-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_user'),
        ('bookings', '0017_bookinghold_refunded_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(choices=[('refund', 'Refund'), ('reschedule', 'Reschedule')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incident_resolution', to='bookings.booking')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='bookings.incident')),
                ('replacement_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_rescheduled_bookings', to='companies.trip')),
            ],
        ),
    ]
