# Generated by Django 4.2.7 on 2026-09-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_route_end_latitude_route_end_longitude_and_more'),
        ('bookings', '0018_incidentresolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='companies.pickupstage'),
        ),
    ]
