# Generated by Django 5.2.18 on 2026-10-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_booking_pickup_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
