# Generated by Django 5.2.18 on 2026-10-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_payout_ledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='fee_percent',
        ),
        migrations.AddField(
            model_name='payout',
            name='fee_per_seat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
