# Generated by Django 5.2.18 on 2026-10-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_payout_flat_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnappliedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('retry', 'Retry'), ('refund_due', 'Refund due'), ('refunding', 'Refund claimed'), ('refunded', 'Refund sent'), ('review', 'Needs review'), ('applied', 'Applied')], default='retry', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('refund_status', models.CharField(blank=True, max_length=20)),
                ('refund_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
