# Generated by Django 5.2.18 on 2026-10-07 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_unapplied_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PayoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10)),
                ('object_id', models.PositiveBigIntegerField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='bookings.payout')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'object_id'), name='uniq_payout_item')],
            },
        ),
    ]
