# Generated by Django 5.2.18 on 2026-10-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_payout_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardingevent',
            name='method',
            field=models.CharField(choices=[('qr', 'QR Scan'), ('pin', 'PIN Entry'), ('walkin', 'Walk-in at stage')], max_length=10),
        ),
    ]
