# Generated by Django 4.2.7 on 2026-10-07 06:39

import charters.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0003_alter_driver_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0010_company_accepts_charters'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=charters.models.generate_reference, editable=False, max_length=12, unique=True)),
                ('purpose', models.CharField(max_length=200)),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('depart_at', models.DateTimeField()),
                ('return_at', models.DateTimeField(blank=True, null=True)),
                ('passenger_count', models.PositiveIntegerField()),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='requested', max_length=12)),
                ('quote_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quote_valid_until', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=300)),
                ('provider_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charter_requests', to='companies.company')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charters', to='drivers.driver')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charter_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='charters_ch_status_2f7cba_idx'), models.Index(fields=['company', 'status'], name='charters_ch_company_3761b7_idx'), models.Index(fields=['driver', 'status'], name='charters_ch_driver__6d9355_idx')],
            },
        ),
    ]
