# Generated by Django 4.2.7 on 2026-10-07 06:31

import deliveries.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0009_route_parcel_price_large_route_parcel_price_medium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(default=deliveries.models.generate_tracking_code, editable=False, max_length=12, unique=True)),
                ('handover_pin', models.CharField(default=deliveries.models.generate_handover_pin, editable=False, max_length=6)),
                ('pin_attempts', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('picked_up', 'Picked up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed_delivery', 'Failed delivery'), ('expired', 'Expired')], default='pending_payment', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dropoff_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels_dropped_here', to='companies.pickupstage')),
                ('pickup_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels_picked_up_here', to='companies.pickupstage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_parcels', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='companies.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='deliveries__status_469082_idx'), models.Index(fields=['sender', 'status'], name='deliveries__sender__d6b803_idx')],
            },
        ),
    ]
