# Generated by Django 5.2.18 on 2026-10-09 14:22

from django.db import migrations, models


def clear_legacy_location_timestamps(apps, schema_editor):
    Driver = apps.get_model("drivers", "Driver")
    Driver.objects.update(location_updated_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            clear_legacy_location_timestamps,
            migrations.RunPython.noop,
        ),
    ]
