import { useCallback, useEffect, useState } from 'react';
import { apiRequest } from '../../api';
import { useAuth } from '../../context/AuthContext';

const date=v=>v?new Date(v).toLocaleString('en-KE',{dateStyle:'medium',timeStyle:'short'}):'—';
function Shell({user,logout,children}){return <div className="page"><div className="shell"><header className="topbar"><div className="brand"><div className="brand-icon">C</div><div>CONNECT<small>Driver portal</small></div></div><div className="top-actions"><span className="location-chip">🚌 {user?.name}</span><button className="btn btn-ghost" onClick={logout}>Logout</button></div></header>{children}</div></div>}
export default function DriverDashboard(){
 const {user,logout}=useAuth(); const [driver,setDriver]=useState(null),[bookings,setBookings]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[location,setLocation]=useState(null);
 const load=useCallback(async()=>{try{const d=await apiRequest('/drivers/me/');setDriver(d);const b=await apiRequest(`/bookings/driver/${d.id}/`);setBookings(b||[])}catch(e){setError(e.message)}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const locate=()=>navigator.geolocation?.getCurrentPosition(async p=>{try{const d=await apiRequest(`/drivers/${driver.id}/location/`,{method:'POST',body:{latitude:p.coords.latitude,longitude:p.coords.longitude}});setLocation(d)}catch(e){setError(e.message)}},()=>setError('Location permission was not granted.'));
 const board=async(id)=>{const pin=prompt('Enter passenger boarding PIN:');if(!pin)return;try{await apiRequest(`/bookings/${id}/verify-boarding/`,{method:'POST',body:{pin}});load()}catch(e){setError(e.message)}};
 return <Shell user={user} logout={logout}><section className="hero"><p className="eyebrow">DRIVER DASHBOARD</p><h1>{driver?.name||'Your driver portal'}</h1><p className="muted">Manage your assigned passengers, update your location and verify boarding.</p></section>{error&&<div className="error">{error}</div>}
 <div className="kpi-row" style={{marginTop:16}}><div className="card stat"><div className="stat-label">Company</div><div className="stat-value" style={{fontSize:18}}>{driver?.company_name||'—'}</div></div><div className="card stat"><div className="stat-label">Bus</div><div className="stat-value">{driver?.bus_number||'—'}</div></div><div className="card stat"><div className="stat-label">Assigned</div><div className="stat-value">{bookings.length}</div></div><div className="card stat"><div className="stat-label">Availability</div><div className="stat-value" style={{fontSize:18}}>{driver?.is_available?'Available':'Unavailable'}</div></div></div>
 <div className="section-title"><h2>Driver tools</h2></div><div className="grid grid-2"><div className="card"><h3>Share live location</h3><p className="muted">Allow the phone's GPS to update your current driver position.</p><button className="btn btn-primary" onClick={locate} disabled={!driver}>Update location</button>{location&&<div className="success">Location updated at {date(location.location_updated_at)}</div>}</div><div className="card"><h3>Boarding</h3><p className="muted">Use the passenger's 4-digit PIN to verify boarding. The backend records the event and updates the integrity flow.</p></div></div>
 <div className="section-title"><h2>Assigned bookings</h2><button className="btn btn-ghost" onClick={load}>Refresh</button></div>{loading?<div className="empty">Loading…</div>:!bookings.length?<div className="empty">No active assigned bookings.</div>:<div className="grid booking-grid">{bookings.map(b=><div className="card" key={b.booking_id}><div className="trip-top"><strong>{b.booking_number}</strong><span className={`badge ${b.status==='confirmed'?'badge-green':'badge-amber'}`}>{b.status}</span></div><h3>{b.passenger}</h3><p className="muted">{b.route}</p><p>📍 {b.pickup_location} • {b.seats} seat(s)</p><div className="nav-pills"><span className="nav-pill">Payment: {b.payment_status}</span>{b.departure_at&&<span className="nav-pill">{date(b.departure_at)}</span>}</div>{b.status==='confirmed'&&<button className="btn btn-primary" style={{marginTop:14}} onClick={()=>board(b.booking_id)}>Verify boarding</button>}</div>)}</div>}
 </Shell>
}
