# Generated by Django 4.2.7 on 2026-09-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_route_end_latitude_route_end_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupstage',
            name='source',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='pickupstage',
            name='source_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
