# Generated by Django 4.2.7 on 2026-10-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_pickupstage_source_pickupstage_source_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='parcel_price_large',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='parcel_price_medium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='parcel_price_small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
