# Generated by Django 4.2.7 on 2026-10-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_route_parcel_price_large_route_parcel_price_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accepts_charters',
            field=models.BooleanField(default=False),
        ),
    ]
