# Generated by Django 5.2.18 on 2026-10-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_accepts_charters'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='via_points',
            field=models.JSONField(blank=True, default=list, help_text='Road points the manager placed to steer the line.', null=True),
        ),
    ]
