import { useCallback, useEffect, useState } from 'react';
import { apiRequest } from '../../api';
import { useAuth } from '../../context/AuthContext';
const money=v=>`KES ${Number(v||0).toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2})}`;const date=v=>v?new Date(v).toLocaleString('en-KE',{dateStyle:'medium',timeStyle:'short'}):'—';
function Shell({user,logout,children}){return <div className="page"><div className="shell"><header className="topbar"><div className="brand"><div className="brand-icon">C</div><div>CONNECT<small>Company management</small></div></div><div className="top-actions"><span className="location-chip">🏢 {user?.company_name||'Company'}</span><button className="btn btn-ghost" onClick={logout}>Logout</button></div></header>{children}</div></div>}
export default function CompanyManagerDashboard(){const{user,logout}=useAuth();const[id]=[user?.company_id];const[analytics,setAnalytics]=useState(null),[trips,setTrips]=useState([]),[drivers,setDrivers]=useState([]),[bookings,setBookings]=useState([]),[routes,setRoutes]=useState([]),[form,setForm]=useState({route_id:'',driver_id:'',departure_at:'',capacity:14}),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const load=useCallback(async()=>{if(!id)return;try{const[a,t,d,b,r]=await Promise.all([apiRequest(`/companies/${id}/analytics/`),apiRequest(`/companies/${id}/trips/`),apiRequest(`/drivers/?company_id=${id}`),apiRequest(`/bookings/all/?company_id=${id}`),apiRequest(`/companies/${id}/routes/`)]);setAnalytics(a);setTrips(t||[]);setDrivers(d||[]);setBookings(b||[]);setRoutes(r||[])}catch(e){setError(e.message)}},[id]);useEffect(()=>{load()},[load]);
 const create=async e=>{e.preventDefault();setError('');try{await apiRequest('/companies/trips/create/',{method:'POST',body:{company_id:id,...form,capacity:Number(form.capacity),departure_at:new Date(form.departure_at).toISOString()}});setSuccess('Trip created.');setForm({route_id:'',driver_id:'',departure_at:'',capacity:14});load()}catch(e){setError(e.message)}};
 const status=async(t,s)=>{try{await apiRequest(`/companies/trips/${t.id}/status/`,{method:'POST',body:{status:s}});load()}catch(e){setError(e.message)}};
 const assign=async b=>{const driverId=prompt(`Driver ID for ${b.booking_number}:`,drivers[0]?.id||'');if(!driverId)return;try{await apiRequest(`/bookings/${b.booking_id}/assign-driver/`,{method:'POST',body:{driver_id:Number(driverId)}});load()}catch(e){setError(e.message)}};
 const confirmCash=async b=>{if(!window.confirm(`Confirm cash payment for ${b.booking_number}? This marks it paid and lets the passenger board.`))return;try{await apiRequest(`/bookings/payments/${b.booking_id}/cash/confirm/`,{method:'POST'});setSuccess(`Cash payment confirmed for ${b.booking_number}.`);load()}catch(e){setError(e.message)}};
 return <Shell user={user} logout={logout}><section className="hero"><p className="eyebrow">COMPANY MANAGER</p><h1>{analytics?.company_name||user?.company_name||'Your company'}</h1><p className="muted">Run departures, assign drivers and monitor bookings from one responsive workspace.</p></section>{error&&<div className="error">{error}</div>}{success&&<div className="success">{success}</div>}
 <div className="kpi-row" style={{marginTop:16}}>{[['Routes',analytics?.total_routes],['Trips',analytics?.total_trips],['Active bookings',analytics?.active_bookings],['Settled revenue',money(analytics?.total_revenue_settled)]].map(([l,v])=><div className="card stat" key={l}><div className="stat-label">{l}</div><div className="stat-value" style={l==='Settled revenue'?{fontSize:19}:undefined}>{v??'—'}</div></div>)}</div>
 <div className="section-title"><h2>Create departure</h2></div><form className="card grid grid-2" onSubmit={create}><label className="field">Route<select className="select" value={form.route_id} onChange={e=>setForm({...form,route_id:e.target.value})} required><option value="">Choose route</option>{routes.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="field">Driver<select className="select" value={form.driver_id} onChange={e=>setForm({...form,driver_id:e.target.value})} required><option value="">Choose driver</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.name} • {d.bus_number}</option>)}</select></label><label className="field">Departure<input className="input" type="datetime-local" value={form.departure_at} onChange={e=>setForm({...form,departure_at:e.target.value})} required/></label><label className="field">Capacity<input className="input" type="number" min="1" max="100" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})} required/></label><button className="btn btn-primary" type="submit">Create trip</button></form>
 <div className="section-title"><h2>Trips</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Route</th><th>Departure</th><th>Driver</th><th>Status</th><th>Action</th></tr></thead><tbody>{trips.map(t=><tr key={t.id}><td>{t.route_details?.name}</td><td>{date(t.departure_at)}</td><td>{t.driver_name}</td><td><span className="badge badge-blue">{t.status}</span></td><td><select className="select" value={t.status} onChange={e=>status(t,e.target.value)}><option>scheduled</option><option>boarding</option><option>departed</option><option>completed</option><option>cancelled</option></select></td></tr>)}</tbody></table></div>
 <div className="section-title"><h2>Bookings</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Booking</th><th>Passenger</th><th>Route</th><th>Payment</th><th>Driver</th><th></th></tr></thead><tbody>{bookings.map(b=><tr key={b.booking_id}><td>{b.booking_number}</td><td>{b.user}<br/><span className="muted">{b.user_phone}</span></td><td>{b.route_name}</td><td>{b.payment_status}{b.payment_method?` · ${b.payment_method}`:''}</td><td>{b.driver_name||'Unassigned'}</td><td><button className="btn btn-secondary" onClick={()=>assign(b)}>Assign</button>{String(b.payment_method).toLowerCase()==='cash'&&String(b.payment_status).toLowerCase()==='pending'&&['pending','confirmed'].includes(String(b.status).toLowerCase())&&<button className="btn btn-primary" style={{marginLeft:6}} onClick={()=>confirmCash(b)}>Confirm cash</button>}</td></tr>)}</tbody></table></div>
 </Shell>}
