# Generated by Django 4.2.7 on 2026-09-24 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('bus_number', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('maintenance_status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], default='operational', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='companies.company')),
            ],
            options={
                'ordering': ['company_id', 'bus_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='bus',
            constraint=models.UniqueConstraint(fields=('company', 'bus_number'), name='unique_bus_number_per_company'),
        ),
    ]
