# Generated by Django 6.1.1 on 2026-09-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_boarded_count_customuser_no_show_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Driver'), ('company_admin', 'Company Admin'), ('platform_admin', 'Platform Admin')], default='passenger', max_length=20),
        ),
    ]
