# Generated by Django 4.2.7 on 2026-09-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Driver'), ('company_manager', 'Company Manager'), ('company_auditor', 'Company Auditor'), ('company_operator', 'Company Operator'), ('platform_admin', 'Platform Admin')], default='passenger', max_length=20),
        ),
    ]
