# Generated by Django 5.2.18 on 2026-10-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_route_via_points'),
        ('users', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='all_routes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='assigned_routes',
            field=models.ManyToManyField(blank=True, related_name='assigned_operators', to='companies.route'),
        ),
    ]
