# Generated by Django 6.1.1 on 2026-09-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('hold', 'Hold'), ('release', 'Release'), ('refund', 'Refund'), ('credit', 'Credit'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
